<section id="bg-contact" class="d-flex align-items-center">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 d-flex justify-content-center text-center">
                <h2 class="text-uppercase">Términos y condiciones</h2>
            </div>
        </div>
    </div>
</section>

<section id="distribution" class="bg-brands">
    <div class="container">
        <div class="row py-5 px-movil">
            <div class="col-12 bg-white rounded brands border">
                <div class="p-4 text-distribution">
                    <div class="d-block">
                    <p>LEGAL</p>
                        <p class="text-justify">Mediante el uso de este sitio web (“sitio web”) de NAtura y MAS (“NATURA”), el cliente o usuario registrado según sea el caso (“usted”), acuerda obligarse conforme a la versión vigente de los términos de uso que aquí se estipulan y acepta ser una persona mayor de 18 años con capacidad, responsabilidad y conocimiento para realizar transacciones y pagos en línea.</p>
                        <p>USO DEL MATERIAL</p>
                        <p class="text-justify">Todos los materiales incluidos en el sitio web de NATURA están protegidos por derechos de autor, marcas registradas y otras leyes, y son propiedad de NATURA y sus proveedores, a menos que se especifique otra cosa. El uso no autorizado de dichos materiales podría infringir las leyes de derechos de autor, de marcas y otras leyes. Usted puede descargar e imprimir partes de los materiales para uso no comercial y para uso informativo. Toda copia que usted haga de dicho material deberá mostrar el correspondiente aviso sobre derechos de autor, marca registrada u otro aviso de propiedad registrada, los cuales se encuentran en el sitio web de NATURA y que correspondan al material que se esté copiando. Se prohíbe cualquier otra acción como la venta, modificación, reproducción, redistribución, publicación o retransmisión de información consignada en el sitio web de NATURA, total o parcialmente, sin el previo consentimiento por escrito de NAtura y MAS.</p>
                        <p>LIMITACIÓN DE RESPONSABILIDAD</p>
                        <p class="text-justify">La información y los servicios publicados en el sitio web de NATURA pueden contener errores tipográficos o imprecisiones técnicas. La información puede cambiar o ser actualizada sin previo aviso. NATURA además puede hacer mejoras y/o cambios en la información descrita en el sitio web de NATURA, en cualquier momento y sin previo aviso. NATURA no se hace responsable de los errores u omisiones que puedan existir en el sitio web de NATURA o en cualquier otro sitio web al que se pueda hacer referencia en su sitio web o que esté enlazado al sitio web de NATURA .</p>
                        <p class="text-justify">LA INFORMACIÓN CONTENIDA EN EL SITIO WEB DE NATURA SE PROPORCIONA “TAL Y COMO ESTÁ”, SIN GARANTÍA DE NINGUNA CLASE, EXPRESA O IMPLÍCITA, INCLUYENDO, DE MANERA ENUNCIATIVA MÁS NO LIMITATIVA, GARANTÍAS IMPLÍCITAS DE COMERCIALIZACIÓN, ADECUACIÓN PARA UN FIN DETERMINADO, NO VULNERACIÓN O TITULARIDAD. NATURA NO GARANTIZA LA EXACTITUD, CONFIABILIDAD, OPORTUNIDAD NI COMPLETITUD DE MATERIAL ALGUNO, YA SEA CONTENIDO EN SU SITIO WEB O AL QUE SE HAYA TENIDO ACCESO A TRAVÉS DEL MISMO. LA DEPENDENCIA O USO DE DICHO MATERIAL SERÁ BAJO SU EXCLUSIVO RIESGO. NATURA NO GARANTIZA QUE EL SITIO WEB NATURA ESTÉ DISPONIBLE DE MANERA OPORTUNA COMO TAMPOCO GARANTIZA LA USENCIA DE INTERRUPCIONES O ERRORES. TAMPOCO GARANTIZA QUE LOS DEFECTOS SEAN CORREGIDOS NI QUE EL SITIO WEB O LOS SERVIDORES QUE HOSPEDAN ESE SITIO WEB ESTÉN LIBRES DE VIRUS U OTROS COMPONENTES PERJUDICIALES.</p>
                        <p class="text-justify">NATURA NO ASUME RESPONSABILIDAD ALGUNA POR NINGÚN TIPO DE DAÑO, INCLUYENDO, DE MANERA ENUNCIATIVA MÁS NO LIMITATIVA, DAÑOS INDIRECTOS, ESPECIALES, CONSECUENCIALES, PUNITIVOS O INCIDENTALES, DE CLASE ALGUNA, ASÍ COMO TAMPOCO POR LA PÉRDIDA DE UTILIDADES, PÉRDIDA DE PROGRAMAS O CUALQUIER OTRA INFORMACIÓN, YA SEA POR RESPONSABILIDAD CONTRACTUAL O EXTRACONTRACTUAL, DERIVADA DEL USO O RELACIONADA CON EL USO O INCAPACIDAD DE USO DEL SITIO WEB DE NATURA O CON EL USO, DEPENDENCIA O DESEMPEÑO DE CUALQUIER MATERIAL CONTENIDO EN EL SITIO WEB DE NATURA O AL QUE SE HAYA TENIDO ACCESO A TRAVÉS DEL MISMO, INCLUSO SI NATURA EXPRESAMENTE ADVIERTE SOBRE LA POSIBILIDAD DE DICHOS DAÑOS.</p>
                        <p>JURISDICCIÓN</p>
                        <p class="text-justify">Los materiales contenidos en el sitio web de NATURA se presentan con la exclusiva finalidad de promover, vender entregar los productos disponibles solamente en la República Mexicana. LOS PRODUCTOS PROMOCIONADOS EN EL SITIO WEB DE NATURA NO SON APTOS PARA SU VENTA FUERA DE MÉXICO. NATURA no garantiza que los materiales incluidos en el sitio web de NATURA cumplan con las leyes de jurisdicciones fuera de su país de residencia. Los individuos que decidan acceder al sitio web de NATURA desde un país diferente lo hacen bajo su propia iniciativa y solo para fines informativos. Los términos y condiciones aquí establecidos se rigen por las leyes mexicanas, sin importar los principios de conflicto de legislación de su país de origen. Por este acto usted se somete a la jurisdicción de los tribunales de México para efectos del litigio de cualquier demanda derivada de estos términos y condiciones o relacionada con los mismos.</p>
                        <p>INSCRIPCIÓN O REGISTRO.</p>
                        <p class="text-justify">El Cliente deberá completar el formulario de inscripción con su información personal de manera exacta, precisa y verdadera (los "Datos Personales") para poder utilizar los servicios de compra de productos que se ofrecen a través del sitio web NATURA ya que de lo contrario no podemos validar la identidad del cliente y por tanto no estaremos en la disposición de otorgar el servicio requerido.</p>
                        <p class="text-justify">Una vez inscrito en el sitio web NATURA, usted autoriza a NATURA a que utilice diversos medios para identificar sus datos personales, y asume el compromiso de actualizar y/o rectificar los Datos Personales conforme resulte necesario.</p>
                        <p>DECLARACION DE ACEPTACIÓN.</p>
                        <p class="text-justify">El Cliente declara que acepta los precios de los productos o mercancías seleccionados, el importe total generado de la compra y costos derivados del envío de mercancía hasta el o los domicilios destino registrados.</p>
                        <p>FACTURACIÓN.</p>
                        <p class="text-justify">Por disposiciones del SAT (Sistema de Administración Tributaria) en México, si requiere factura usted está obligado a proporcionar a NATURA los datos fiscales necesarios para realizar la facturación de su compra tales como RFC (Copia de registro de inscripción al registro federal de contribuyentes), Régimen fiscal, Nombre completo o razón social, código postal, domicilio fiscal y tipo de uso de la mercancía (Uso del CFDI). Opcionalmente nos podrá proporcionar su número telefónico y una cuenta de correo a donde le serán enviadas sus facturas. Todos los datos proporcionados se mantendrán en confidencialidad plena tal y como se menciona en el Aviso de Privacidad.</p>
                        <p>CANCELACIÓNES.</p>
                        <p class="text-justify">Usted podrá realizar la cancelación de su compra hecha a través de la página web de NATURA en un máximo de 4 horas después de haber realizado su compra, siempre y cuando no se haya enviado la mercancía. Una vez recibida la mercancía, ningún reembolso será posible. Para tramitar la cancelación y su respectivo reembolso deberá enviar un correo electrónico a atencionaclientes@NATURA.mx o bien, comunicándose con nosotros vía telefónica al 3339427070. Una vez aceptada la cancelación del pedido, se tramitará su respectivo reembolso mediante transferencia electrónica por el importe del pedido dentro de los siguientes 15 días hábiles a la obtención de sus datos y directamente a la cuenta con la que se realizó la compra. Se requerirá la cuenta clave, nombre del banco, sucursal y nombre del beneficiario para realizar el reembolso, sin estos datos no será posible realizarlo. </p>
                        <p>POLÍTICAS DE DEVOLUCIÓN.</p>
                        <p class="text-justify">Las devoluciones solo aplican en los casos de mercancía con defecto de fábrica o daños en el producto derivados del proceso de envío. Para solicitar la devolución deberá enviar evidencia en fotografía y copia de la factura al departamento de servicio al cliente atencionaclientes@NATURA.mx. No se aceptan devoluciones ocasionadas por mal uso del producto o maltrato intencional. Si el producto no cumple con estas especificaciones, la devolución no podrá ser procesada. Una vez aceptada la devolución, NATURA enviará una guía de paquetería prepagada al cliente y este a su vez después de recibirla deberá enviar el producto en su empaque original en un lapso no mayor a 3 días. Una vez recibida y validada la mercancía se iniciará el trámite de reembolso mediante transferencia electrónica por el importe del pedido dentro de los siguientes 15 días hábiles a la obtención de sus datos y directamente a la cuenta con la que se realizó la compra. Se requerirá la cuenta clave, nombre del banco, sucursal y nombre del beneficiario para realizar el reembolso, sin estos datos no será posible realizarlo. </p>
                        <p>PRIVACIDAD</p>
                        <p class="text-justify">NATURA reconoce la importancia de proteger la privacidad de la información que usted nos proporcione. Para ello, estamos comprometidos a hacer nuestros mejores esfuerzos para respetar su privacidad. Consulte el documento en la liga de Aviso de Privacidad.</p>
                        <p>COOKIES</p>
                        <p class="text-justify">El sitio web de NATURA deposita ciertos bits de información llamados cookies en el software del navegador de quienes visitan su sitio. Las cookies regresan solo al sitio de NATURA que las depositó cuando el visitante regresa a dicho sitio. Las cookies pueden decirnos cómo y cuándo son visitadas las páginas de un sitio de NATURA, así como por cuánta gente son visitadas. NATURA utiliza las cookies para:<br>
                        •Rastrear el estatus de su carrito de compras;<br>
                        •Para permitirle a usted el uso de servicios de protección de contraseña en una sola sesión sin tener que proporcionar de nuevo su contraseña; y<br>
                        •Para rastrear su sitio de origen para la función "sígueme".<br></p>
                        <p>MENORES DE EDAD.</p>
                        <p class="text-justify">NATURA no solicita información personal de menores de 18 años ni vende sus productos a menores de 18 años. Toda compra deberá hacerse por una persona mayor de edad tal y como se menciona en el apartado LEGAL. NATURA no se hace responsable por transacciones realizadas o actos perjudiciales a menores de edad supervisados o no por sus padres o tutores.</p>
                        <p>PREVENCIÓN DE DELITOS.</p>
                        <p class="text-justify">Usted deberá tener la precaución de implementar en sus dispositivos en los cuales realizará sus compras en el sitio web de NATURA, los programas antivirus, antiespías y escudos de protección activados para evitar el robo de información introducida en el portal de NATURA.</p>
                        <p>ENLACES A OTROS SITIOS WEB</p>
                        <p class="text-justify">Como recursos para nuestros visitantes, NATURA proporciona enlaces a otros sitios web que creemos serán de utilidad y que cumplen con nuestros altos estándares. Sin embargo, NATURA no se hace responsable de los contenidos de dichos sitios web. En particular, NATURA no se hace responsable de los avisos de privacidad ni de las prácticas de privacidad que ofrecen dichos sitios web con los que se haga enlace.</p>
                        <p>NOTIFICACIONES</p>
                        <p class="text-justify">NATURA podrá enviar a su cuenta de correo notificaciones acerca de nuestros productos y promociones. NATURA le da la oportunidad de cancelar la recepción de futuros comunicados enviados por correo electrónico. Esto le da la opción de eliminar su dirección de correo electrónico de nuestra base de datos de manera que no reciba ningún correo futuro y ya no reciba nuestro servicio.</p>
                        <p class="text-justify">Puede hacer uso de esta opción en cualquier momento haciéndonos llegar un correo electrónico o una carta dirigida a nuestro departamento de Servicio al Cliente a través de la cuenta de atencionaclientes@NATURA.mx.  Si cancela el servicio no podrá utilizar las áreas protegidas por contraseña de nuestro sitio.</p>
                        <p>ACCESO A INFORMACIÓN PERSONAL</p>
                        <p class="text-justify">Usted tiene derecho a solicitar y obtener de NATURA la información personal que NATURA tiene en archivo sobre usted y solicitar una corrección de cualquier dato que sea inexacto. También puede solicitar a NATURA que le informe el tipo de información personal que tiene en su poder. La solicitud de acceso a datos personales y la corrección de datos personales o información acerca de las políticas y procedimientos de NATURA sobre datos personales deberá hacerse por escrito y dirigirse al departamento de Servicio a Clientes de NATURA.</p>
                        <p class="text-justify">Cualquier pregunta o comentario acerca de NATURA deberá enviarse por escrito o por correo postal al Servicio de Atención a Clientes.</p>
                        <p>COMUNICACIÓN ELECTRÓNICA COMERCIAL NO SOLICITADA (SPAM)</p>
                        <p class="text-justify">NATURA no envía “spam” (comunicación electrónica comercial no solicitada en forma de correo electrónico, textos, mensajes SMS/instantáneos) a nuestros clientes. Si usted recibe información con títulos o pseudónimos en nuestro nombre deberá reportarlos de manera oportuna a nuestro departamento de Servicio al Cliente.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
